#!/usr/bin/python3

import os
from library import make_dockerfile

for target in os.listdir("."):
    if (
        os.path.isdir(target)
        and target != ".venv"
        and target != ".git"
        and not target.startswith("__pycache")
    ):
        make_dockerfile(target)
